### ISSUE TITLE
Redireccionar pantalla de deteccion de cara hacia la web

### ISSUE THREAD

**Issue by enzoftware** [boxting/face_recognition#4]
Desarrollar una aplicacion de escritorio que cumpla con:

- Reconocer la cara 
- Votar **(Realizar conexion http con el servicio blockchain desplegado o local)**
- Mostrar stats de las votaciones **(Realizar conexion http con el servicio blockchain desplegado o local)**

**Comment by enzoftware** [comment]
Recursos de utilidad:
 - https://www.cosc.canterbury.ac.nz/greg.ewing/python_gui/
- https://kivy.org/#home

**Comment by enzoftware** [comment]
Otra opcion es utilizar `identify_face_camera.py` y cuando detecte una cara te redireccione hacia tu navegador para poder realizar la votacion

**Comment by enzoftware** [comment]
Cambio de asignados por complejidad minima

**Comment by enzoftware** [comment]
- Cambiar modelo de guardado de carpetas de nombre a DNI . Ejemplo : `71930207/p1.jpg`
- Al detectar una cara que cumpla con un accuracy mayor al 95%, te redirecciona a una pagina para votar.

**Comment by RodrigoAGM** [comment]
Done.
